# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxfaR52jxpH5M-1avijroLpNq1od44_B
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

def google_news_osint_cek():
    # Google News RSS üzerinden "Hürmüz Boğazı" araması (Türkçe kaynaklar)
    url = "https://news.google.com/rss/search?q=Hürmüz+Boğazı&hl=tr&gl=TR&ceid=TR:tr"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        # RSS bir XML formatı olduğu için 'xml' modunda okuyoruz
        soup = BeautifulSoup(response.content, 'xml')

        # RSS içindeki her bir haber 'item' etiketi içinde tutulur
        haber_kartlari = soup.find_all('item')

        haber_listesi = []

        # Çektiğimiz haberleri tek tek dönüp ayıklıyoruz
        for kart in haber_kartlari:
            baslik = kart.find('title').text if kart.find('title') else 'Başlık Yok'
            link = kart.find('link').text if kart.find('link') else 'Link Yok'
            yayin_tarihi = kart.find('pubDate').text if kart.find('pubDate') else 'Tarih Yok'

            haber_listesi.append({
                'Cekilme_Zamani': datetime.now().strftime("%Y-%m-%d %H:%M"),
                'Yayin_Tarihi': yayin_tarihi,
                'Haber_Basligi': baslik,
                'Haber_Linki': link
            })

        return haber_listesi

    except Exception as e:
        print(f"Veri çekilirken kritik bir hata oluştu: {e}")
        return []

# Kodu test etme
if __name__ == "__main__":
    print("OSINT Veri Toplama Başlıyor... Google Haberler Taranıyor 🌍")
    toplanan_veriler = google_news_osint_cek()

    if toplanan_veriler:
        # Verileri Pandas DataFrame'e çevir
        df = pd.DataFrame(toplanan_veriler)

        # Sonuçları csv olarak kaydet
        dosya_adi = 'hurmuz_osint_verileri.csv'
        df.to_csv(dosya_adi, index=False, encoding='utf-8')

        print(f"Başarılı! Toplam {len(toplanan_veriler)} adet haber bulundu.")
        print(f"Veriler '{dosya_adi}' dosyasına kaydedildi!")

        # Ekranda ilk 3 haberi görelim
        print("\n--- ÇEKİLEN İLK 3 HABER ÖZETİ ---")
        print(df[['Haber_Basligi', 'Yayin_Tarihi']].head(3).to_string(index=False))
    else:
        print("Herhangi bir veri bulunamadı.")

from wordcloud import WordCloud
import matplotlib.pyplot as plt
import pandas as pd

print("Metin Madenciliği Başlıyor: Haber başlıkları analiz ediliyor...\n")

# Az önce kaydettiğimiz dosyayı okuyoruz
df = pd.read_csv('hurmuz_osint_verileri.csv')

# Tüm haber başlıklarını tek bir devasa metin haline getiriyoruz
butun_metin = " ".join(baslik for baslik in df['Haber_Basligi'])

# 'Hürmüz', 'Boğazı', 'Haber' gibi arama yaptığımız kelimeleri ve
# 've, bir, için' gibi bağlaçları buluttan çıkarıyoruz ki asıl olaylar (kriz, petrol, gemi vb.) öne çıksın
gereksiz_kelimeler = set(['ve', 'bir', 'için', 'ile', 'bu', 'da', 'de', 'göre', 'kadar', 'sonra',
                          'olarak', 'olan', 'gibi', 'en', 'çok', 'Hürmüz', 'Boğazı', 'Haber',
                          'Son', 'Dakika', 'Haberleri', 'Boğazı\'nı', 'Boğazı\'nda'])

# Kelime Bulutunu oluşturma ayarları (Siyah arkaplan siber güvenlik temasına çok yakışır!)
wordcloud = WordCloud(width=1000, height=500,
                      background_color='black',
                      colormap='Oranges', # Turuncu-Ateş rengi teması (kriz/uyarı hissi verir)
                      stopwords=gereksiz_kelimeler,
                      min_font_size=10).generate(butun_metin)

# Görseli ekrana çizdirme
plt.figure(figsize=(12, 6), facecolor=None)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.tight_layout(pad=0)

# Görseli bilgisayara indirmek için dosya olarak kaydet
plt.savefig('osint_kelime_bulutu.png')

print("Harika! Kelime bulutu 'osint_kelime_bulutu.png' olarak kaydedildi.")
plt.show()

import socket
import requests
import folium
import pandas as pd
import warnings
warnings.filterwarnings('ignore') # Terminaldeki gereksiz uyarıları gizler

print("🚀 Gelişmiş Siber Keşif Aracı Başlatılıyor...")
print(" Hedef: Hürmüz Boğazı Denizcilik ve İstihbarat Altyapıları")
print("-" * 70)

# Genişletilmiş Hedef Listesi
hedef_domainler = {
    "İran Limanlar Kurumu": "pmo.ir",
    "BAE DP World (Dev Liman)": "dpworld.com",
    "Umman Limanları": "asyad.om",
    "Kuveyt Liman İdaresi": "kpa.gov.kw",
    "Suudi Arabistan Limanları": "mawani.gov.sa",
    "Katar Liman Yönetimi": "mwani.com.qa",
    "Bahreyn Limanları": "mtt.gov.bh",
    "MarineTraffic (OSINT Aracı)": "marinetraffic.com",
    "VesselFinder (OSINT Aracı)": "vesselfinder.com",
    "ABD 5. Filo (Bahreyn Üssü)": "cusnc.navy.mil"
}

osint_sonuclari = []

# Harita oluşturma (Karanlık siber tema)
siber_harita = folium.Map(location=[26.56, 56.25], zoom_start=5, tiles="CartoDB dark_matter")

for kurum, domain in hedef_domainler.items():
    try:
        # 1. IP Tespiti (DNS Recon)
        ip_adresi = socket.gethostbyname(domain)

        # 2. Coğrafi Konum Tespiti (IP Geolocation)
        geo_yanit = requests.get(f"http://ip-api.com/json/{ip_adresi}").json()

        # 3. Banner Grabbing (Sunucu Teknolojisini Çalma)
        # Sitelere bot değilmişiz gibi gidip 'Server' bilgisini çekiyoruz
        headers = {'User-Agent': 'Mozilla/5.0'}
        try:
            http_yanit = requests.get(f"https://{domain}", headers=headers, timeout=5, verify=False)
            sunucu_bilgisi = http_yanit.headers.get('Server', 'Gizlenmiş/Bulunamadı')
        except:
            sunucu_bilgisi = "Bağlantı Reddedildi (Muhtemel Güvenlik Duvarı)"

        if geo_yanit.get('status') == 'success':
            ulke = geo_yanit['country']
            sehir = geo_yanit['city']
            isp = geo_yanit['isp']
            lat = geo_yanit['lat']
            lon = geo_yanit['lon']

            # Haritaya ekleme
            popup_bilgi = f"""
            <div style='width:200px'>
            <b>🏛️ {kurum}</b><br>
            <b>🔗 Domain:</b> {domain}<br>
            <b>🌐 IP:</b> {ip_adresi}<br>
            <b>📍 Konum:</b> {ulke} / {sehir}<br>
            <b>🏢 ISP:</b> {isp}<br>
            <b>💻 Sunucu:</b> <span style='color:red;'>{sunucu_bilgisi}</span>
            </div>
            """

            folium.Marker(
                location=[lat, lon],
                popup=popup_bilgi,
                icon=folium.Icon(color='red', icon='crosshairs', prefix='fa')
            ).add_to(siber_harita)

            osint_sonuclari.append({
                "Kurum": kurum, "Domain": domain, "IP Adresi": ip_adresi,
                "Ülke": ulke, "ISP": isp, "Sunucu Teknolojisi": sunucu_bilgisi
            })

            # Terminale havalı log yazdırma
            print(f"[+] {kurum} ({domain})")
            print(f"    ↳ IP: {ip_adresi} | Konum: {ulke} ({isp})")
            print(f"    ↳ Sunucu: {sunucu_bilgisi}\n")

    except Exception as e:
        print(f"[-] {kurum} ({domain}) hedefinde hata: Hedef kendini gizliyor olabilir.\n")

print("-" * 70)
# Tabloyu ve Haritayı Kaydetme
df_altyapi = pd.DataFrame(osint_sonuclari)
df_altyapi.to_csv('maritime_cyber_infrastructure_pro.csv', index=False)
siber_harita.save("siber_altyapi_haritasi_pro.html")

print("✔️ Ağ keşfi tamamlandı!")
print("✔️ 'maritime_cyber_infrastructure_pro.csv' ve 'siber_altyapi_haritasi_pro.html' kaydedildi.")